#ifndef GTDRAG_INTERFACE_DEF_H
#define GTDRAG_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_GTDRAG_H
#include <libraries/gtdrag.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct GtdragIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct GtdragIFace *Self);
	ULONG APICALL (*Release)(struct GtdragIFace *Self);
	void APICALL (*Expunge)(struct GtdragIFace *Self);
	struct Interface * APICALL (*Clone)(struct GtdragIFace *Self);
	struct IntuiMessage * APICALL (*GTD_GetIMsg)(struct GtdragIFace *Self, struct MsgPort * iport);
	void APICALL (*GTD_ReplyIMsg)(struct GtdragIFace *Self, struct IntuiMessage * msg);
	struct IntuiMessage * APICALL (*GTD_FilterIMsg)(struct GtdragIFace *Self, struct IntuiMessage * msg);
	struct IntuiMessage * APICALL (*GTD_PostFilterIMsg)(struct GtdragIFace *Self, struct IntuiMessage * msg);
	void APICALL (*Reserved54)(struct GtdragIFace *Self);
	void APICALL (*Reserved60)(struct GtdragIFace *Self);
	int APICALL (*GTD_AddAppA)(struct GtdragIFace *Self, STRPTR name, struct TagItem * tagList);
	int APICALL (*GTD_AddApp)(struct GtdragIFace *Self, STRPTR name, ...);
	void APICALL (*GTD_RemoveApp)(struct GtdragIFace *Self);
	void APICALL (*GTD_AddWindowA)(struct GtdragIFace *Self, struct Window * win, struct TagItem * tagList);
	void APICALL (*GTD_AddWindow)(struct GtdragIFace *Self, struct Window * win, ...);
	void APICALL (*GTD_RemoveWindow)(struct GtdragIFace *Self, struct Window * win);
	void APICALL (*GTD_AddGadgetA)(struct GtdragIFace *Self, ULONG type, struct Gadget * gad, struct Window * win, struct TagItem * tagList);
	void APICALL (*GTD_AddGadget)(struct GtdragIFace *Self, ULONG type, struct Gadget * gad, struct Window * win, ...);
	void APICALL (*GTD_RemoveGadget)(struct GtdragIFace *Self, struct Gadget * gad);
	void APICALL (*GTD_RemoveGadgets)(struct GtdragIFace *Self, struct Window * gad);
	void APICALL (*GTD_SetAttrsA)(struct GtdragIFace *Self, APTR gad, struct TagItem * tags);
	void APICALL (*GTD_SetAttrs)(struct GtdragIFace *Self, APTR gad, ...);
	BOOL APICALL (*GTD_GetAttr)(struct GtdragIFace *Self, APTR gad, ULONG d0arg, ULONG * storage);
	struct Hook * APICALL (*GTD_GetHook)(struct GtdragIFace *Self, ULONG num);
	STRPTR APICALL (*GTD_GetString)(struct GtdragIFace *Self, struct ObjectDescription * od, STRPTR buf, LONG len);
	BOOL APICALL (*GTD_PrepareDrag)(struct GtdragIFace *Self, struct Gadget * gad, struct gpInput * gpi);
	BOOL APICALL (*GTD_BeginDrag)(struct GtdragIFace *Self, struct Gadget * gad, struct gpInput * gpi);
	ULONG APICALL (*GTD_HandleInput)(struct GtdragIFace *Self, struct Gadget * gad, struct gpInput * gpi);
	void APICALL (*GTD_StopDrag)(struct GtdragIFace *Self, struct Gadget * gad);
	void APICALL (*FreeTreeList)(struct GtdragIFace *Self, APTR pool, struct TreeList * treelist);
	void APICALL (*InitTreeList)(struct GtdragIFace *Self, struct TreeList * treelist);
	void APICALL (*FreeTreeNodes)(struct GtdragIFace *Self, APTR pool, struct MinList * list);
	struct TreeNode * APICALL (*AddTreeNode)(struct GtdragIFace *Self, APTR pool, struct MinList * tree, STRPTR name, struct Image * image, UWORD flags);
	void APICALL (*CloseTreeNode)(struct GtdragIFace *Self, struct MinList * main, struct TreeNode * treenode);
	LONG APICALL (*OpenTreeNode)(struct GtdragIFace *Self, struct MinList * main, struct TreeNode * treenode);
	LONG APICALL (*ToggleTreeNode)(struct GtdragIFace *Self, struct MinList * main, struct TreeNode * treenode);
	struct TreeNode * APICALL (*GetTreeContainer)(struct GtdragIFace *Self, struct TreeNode * treenode);
	STRPTR APICALL (*GetTreePath)(struct GtdragIFace *Self, struct TreeNode * treenode, STRPTR buffer, LONG len);
	struct TreeNode * APICALL (*FindTreePath)(struct GtdragIFace *Self, struct MinList * tree, STRPTR path);
	struct TreeNode * APICALL (*FindTreeSpecial)(struct GtdragIFace *Self, struct MinList * tree, APTR special);
	struct TreeNode * APICALL (*FindListSpecial)(struct GtdragIFace *Self, struct MinList * list, APTR special);
	BOOL APICALL (*ToggleTree)(struct GtdragIFace *Self, struct Gadget * gad, struct TreeNode * treenode, struct IntuiMessage * msg);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* GTDRAG_INTERFACE_DEF_H */
