/*
**	$Id$
**	Generated by IDLTool 53.1
**	Do not edit
**
**	AutoInit stub for gtdrag
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <intuition/gadgetclass.h>
#include <libraries/gtdrag.h>

#include <interfaces/gtdrag.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * GTDragBase = NULL;
static struct Library * __GTDragBase;

/****************************************************************************/

void gtdrag_base_constructor(void)
{
    if (GTDragBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __GTDragBase = GTDragBase = (struct Library *)IExec->OpenLibrary("gtdrag.library", 0L);
    assert(GTDragBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*gtdrag_base_constructor_ptr)(void) USED = gtdrag_base_constructor;

/****************************************************************************/

void gtdrag_base_destructor(void)
{
    if (__GTDragBase)
    {
        IExec->CloseLibrary((struct Library *)__GTDragBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*gtdrag_base_destructor_ptr)(void) USED = gtdrag_base_destructor;

/****************************************************************************/

